# Generated by Django 3.1.5 on 2021-06-28 17:54

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myutils.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('compare_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('featured', models.BooleanField(blank=True, default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('discount', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=myutils.helpers.upload_prod, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('JPG', 'JPEG', 'PNG'))])),
                ('in_stock', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prods', to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserProductRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(blank=True, default=False)),
                ('in_bookmark', models.BooleanField(blank=True, default=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'OK'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Excellent')], null=True)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='customers',
            field=models.ManyToManyField(related_name='cust_prods', through='products.UserProductRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
